[app]
name = "Sagmi | API Health Checker Service"
run_every_time = 30
restart_in_after_panic = 5
request_timeout = 10
port = "8080"

[database]
name = "database_name"

[slack]
send_alarm = false
webhook_url = "slack_webhook_url"

[logger]
print_in_console = true
save_in_file = false
log_file_path = "./logs/logs.txt"
save_in_database = true

[mailgun]
send_email = false
domain = "example.com"
api_key = "your_mailgun_api_key"
region_is_eu = true
sender = "sender@example.com"
receiver = "receiver@example.com"

[google_cloud]
production_project_url = "google_cloud_production_project_url"